# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1hr3IFR2VtkIfOtoKbuuliPqWotKxpg
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def set_name(self, name):
        self.name = name
    def set_age(self, age):
        self.age = age

    def printinfo(self):
        print("名前:", self.name)
        print("年齢:", self.age)

human = Human("侍", 33)

human.printinfo()