# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/SA901105/38313abdf8a4461fe413f4aa54176eff/kadai_005.ipynb
"""

num = (10 + 20) * 5/2
 print(num, "cm²")