# -*- coding: utf-8 -*-
"""kadai_014

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkylWrG4-Dj7DSrsBe8ImK6NSPXOY8KY
"""

price1 = 100
price2 = 200

def total():
    return price1 + price2

tax = 1.1

print (total() * tax)