# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzoUNSTVP8XjzacrFlbrao0jOKjw-9vk
"""



num = (10 + 20) * 5/2

print(str(num) + "㎠")



num = (10 + 20) * 5/2

print(num , "㎠")

(10 + 20) * 5 / 2