# -*- coding: utf-8 -*-
"""kadai_011.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMi5gZ0heDnEagt0qPwkFEyrdIlNAill
"""

array_lists = ["水","金","地","火","木","土","天","海","冥"]

# for文の場合
for array_list in array_lists:
    print(array_list)

array_lists = ["水","金","地","火","木","土","天","海","冥"]

# while文の場合

# カウンタ変数を用意する
i = 0

# 配列の長さを使ってループを制御する
while i < len(array_lists):
    #   配列の要素を出力する
    print(array_lists[i])
    # インデックスを一つ進める
    i += 1
    # 最後の要素に達したらループを終了する
    if i == len(array_lists):
      break



# このコードでは以下のことが行われています：

# 1.iは0からスタートし、配列array_listsのインデックスとして使用されます。
# 2.whileループはiがarray_listsの長さ未満である間続けられます。
# 3.各ループで、現在の要素array_lists[i]が出力され、その後iがインクリメントされます。
# 4.if文を使って、iが配列の要素数に達したかどうかをチェックし、そうであればループをbreakで抜けます（実際にはこのifは必須ではありませんが、コードの理解を助けるために残しています）。

# このコードは「水金地火木土天海冥」の各文字を一文字ずつ取り出して出力します。

# 自コード　誤り

# 変数numの値が0以外である間、変数numの値を出力し続ける
# while i !=  array_lists[8]:
#    i = i + 1
#    i == array_lists[8]:
#      break