# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzoUNSTVP8XjzacrFlbrao0jOKjw-9vk
"""



(10 + 20) * 5 / 2