# -*- coding: utf-8 -*-
"""kadai_013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DN962zwMpqfIg7Cfy370Wgdxn6WsT5VX
"""

def buy_products(price, tax):
    tax = price * 0.1
    total = price + tax
    print(f"{price}円(税込：{total})円")

buy_products(1000, 100)