# -*- coding: utf-8 -*-
"""kadai_017.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLljYnUkjXydrzm8DB39NfYOtYOv7wpL
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def check_adult(self):
        if self.age >= 20:
            print(f"{self.name}は大人です。")
        else:
            print(f"{self.name}は大人ではありません。")

# Humanクラスのインスタンスを生成し、リストに追加
humans = [
    Human("Taro", 25),
    Human("Hanako", 18),
    Human("Bob", 30)
]

# リストの要素数分だけcheck_adultメソッドを呼び出す
for human in humans:
    human.check_adult()